### ISSUE TITLE
Problem with example code

### ISSUE THREAD

**Issue by MeysemTamaar** [foxik0070/arduino_CH376s#2]
So i connected the CH376 TX to Arduino Mega Serial3 RX and RX to TX, give power and ground, but when i compile the code, i get the following error message:

no matching function for call to 'USB_CH376s::USB_CH376s(HardwareSerial&, HardwareSerial&)'

Looking for support, thanks in advance

**Comment by vladkozlov69** [comment]
@MeysemTamaar actually you should pass pointers, e.g.

USB_CH376s usb(&Serial1, &Serial2);

For MEGA: USB_CH376s usb(&Serial3, &Serial);

**Comment by MeysemTamaar** [comment]
Thanks alot, its working now. If you don't mind i have a small suggestion, please update the example code accordingly.

**Comment by vladkozlov69** [comment]
Sure, will create a pull request for maintainer just now. It was a my typo when I did a refactoring from serials to streams.

**Comment by MeysemTamaar** [comment]
can we use CH376 as simple USB to TTL Converter like CH340G. I wan to use it to program arduino (like CH340G does by simply acting as USB to TTL converter) and also use it to perform data-logging on external USB device. Thanks in advance

**Comment by vladkozlov69** [comment]
I think it can't be used this way. In fact, CH376 is more like as "micro-fileserver" with UART access, and you can't use it in a reverse mode.
